#!/bin/bash

#TODO Check for open files on mountpoints (lsof) & kill associated processes

GPFSBIN=/usr/lpp/mmfs/bin


function get_gpfs_mounts() {
    mount -t gpfs | awk '{print $3}'
}


function get_bindmounts() {
    awk '
        NR==FNR { gpfs_mounts[$1]++; next }
        /bind/ { if ( gpfs_mounts[$2] > 0 ) { print $2 } }
    ' <( get_gpfs_mounts ) /etc/fstab
}


function gpfs_off() {
    $GPFSBIN/mmshutdown
    for i in $(seq 1 10); do sleep 1; printf "."; done
    printf "\n"
    $GPFSBIN/mmgetstate
}


# Attempt to unmount all bind mounts
# Sometimes, multiple bind mounts are present, keep looking until mount count == 1
# or mount count doesn't change after 2 attempts (and exit with an error)
echo
echo "GPFS MOUNTS"
mounts_curr=( $( get_gpfs_mounts ) )
echo "${mounts_curr[@]}"
repeat_attempts=0
while [[ ${#mounts_curr[*]} -gt 1 ]] ; do
    echo "Attempt to unmount '${#mounts_curr[*]}' bind mounts"
    get_bindmounts | xargs -r /bin/umount
    prev_mcount=${#mounts_curr[*]}
    mounts_curr=( $( get_gpfs_mounts ) )
    echo "Current gpfs mounts: '${mounts_curr[@]}'"
    echo "Current gpfs mount count: '${#mounts_curr[*]}'"
    if [[ ${#mounts_curr[*]} -lt $prev_mcount ]] ; then
        echo "resetting attempts counter"
        repeat_attempts=0
    else
        echo "mount count didn't decrease, trying again"
        let "repeat_attempts+=1"
    fi
    if [[ $repeat_attempts -ge 2 ]] ; then
        echo "ERROR: Unable to unmount some bind mounts" >&2
        exit 1
    fi
done

#echo
#echo "GET GPFS MOUNTS"
#get_gpfs_mounts | xargs echo
#
#echo
#echo "UnMOUNT ACTUAL GPFS MOUNTS"
#get_gpfs_mounts | xargs -r $GPFSBIN/mmumount

echo
echo "SHUTDOWN GPFS"
gpfs_off

echo
echo "DONE"
